[package]
org = "peerpressure"
name = "q1_library_client"
version = "0.1.0"
distribution = "2201.13.5"
authors = ["Jaden Awaseb", "Peer Pressure Team"]
keywords = ["dsa", "rest", "library-client", "ballerina", "distributed-systems"]
repository = "https://github.com/CodeGrogu/DSA-Assignment"

[build-options]
observabilityIncluded = true
